### ISSUE TITLE
Container `setRecords` doesn't work since v1.26

### ISSUE THREAD

**Issue by jiedxu** [GAMS-dev/gamspy#30]
Hi, thanks for this nice software.

`setRecords` method of the container doesn't work since v1.26:

```log
>           container.setRecords(data)

tests\e2m2s\views\test_populator.py:83: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.venv\Lib\site-packages\gamspy\_container.py:1638: in setRecords
    symbol._setRecords(record, uels_on_axes=uels_on_axe)
.venv\Lib\site-packages\gamspy\_symbols\set.py:963: in _setRecords
    SetIngestor(self).ingest(records, uels_on_axes=uels_on_axes)
.venv\Lib\site-packages\gamspy\_records_ingestion.py:45: in ingest
    self._from_dataframe(records, uels_on_axes)
.venv\Lib\site-packages\gamspy\_records_ingestion.py:396: in _from_dataframe
    self._from_else(records)
.venv\Lib\site-packages\gamspy\_records_ingestion.py:498: in _from_else
    self._finalize_records(records, col_labels=labels)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <gamspy._records_ingestion.SetIngestor object at 0x000002AA19480DD0>
records =         * element_text
0    2000             
1    2001             
2    2002             
3    2003             
4  ...   
98   2098             
99   2099             
100  2100             
101  2101             

[102 rows x 2 columns]
col_labels = ['*']

    def _finalize_records(
        self, records: pd.DataFrame, col_labels: list[str] | None = None
    ) -> None:
        labels = (
            col_labels
>           if col_labels is not None and not self.symbol._is_miro_symbol
            else self.symbol.domain_names
        )
E       AttributeError: 'Set' object has no attribute '_is_miro_symbol'

.venv\Lib\site-packages\gamspy\_records_ingestion.py:375: AttributeError
```

**Comment by mabdullahsoyturk** [comment]
Thank you. Can you provide a minimum reproducible script so that we can investigate the problem?

**Comment by jiedxu** [comment]
```python
import pandas as pd
from gamspy import Container

container = Container()

container.read("./empty.gdx")

byear = container["byear"]

container.setRecords({byear: pd.DataFrame({"*": [1, 2, 3, 4, 5]})})
```

gets

```
Traceback (most recent call last):
  File "/Users/xxx/Documents/ude-ewl/db/main.py", line 12, in <module>
    container.setRecords({byear: pd.DataFrame({"*": [1, 2, 3, 4, 5]})})
  File "/Users/xxx/Documents/ude-ewl/db/.venv/lib/python3.11/site-packages/gamspy/_container.py", line 1638, in setRecords
    symbol._setRecords(record, uels_on_axes=uels_on_axe)
  File "/Users/xxx/Documents/ude-ewl/db/.venv/lib/python3.11/site-packages/gamspy/_symbols/set.py", line 963, in _setRecords
    SetIngestor(self).ingest(records, uels_on_axes=uels_on_axes)
  File "/Users/xxx/Documents/ude-ewl/db/.venv/lib/python3.11/site-packages/gamspy/_records_ingestion.py", line 45, in ingest
    self._from_dataframe(records, uels_on_axes)
  File "/Users/xxx/Documents/ude-ewl/db/.venv/lib/python3.11/site-packages/gamspy/_records_ingestion.py", line 396, in _from_dataframe
    self._from_else(records)
  File "/Users/xxx/Documents/ude-ewl/db/.venv/lib/python3.11/site-packages/gamspy/_records_ingestion.py", line 498, in _from_else
    self._finalize_records(records, col_labels=labels)
  File "/Users/xxx/Documents/ude-ewl/db/.venv/lib/python3.11/site-packages/gamspy/_records_ingestion.py", line 375, in _finalize_records
    if col_labels is not None and not self.symbol._is_miro_symbol
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Set' object has no attribute '_is_miro_symbol'
```

I got this empty GDX file from some GAMS files:

[empty.gdx.zip](https://github.com/user-attachments/files/30673551/empty.gdx.zip)

But this works fine with v1.25.

---

The issue might be related this particular GDX file somehow, as a new small GDX doesn't seem to cause the issue.

**Comment by mabdullahsoyturk** [comment]
This issue has been fixed in v1.26.4. Thanks for reporting!

**Comment by jiedxu** [comment]
You're welcome. Thanks for fixing it.
